console.log("Hello world");
let a=4;
console.log(typeof(a));
let b=234.6;
console.log(typeof(b));
let c= "Mitu";
console.log(typeof(c));
let required=true;
console.log(typeof(required));
let sum = a+b;
console.log(sum);